In [1]:
import pandas as pd

In [2]:
##------------------------CTG DESCRIPTION
#LB : beats per second
#AC : acceleration per second
#FM : fetal movement per second
#NSP (Normal , suspect, pathalogical)

# CTG

In [3]:
pd.read_csv(r"C:\Users\user\Desktop\MLA\CTG.csv")

       LB     AC     FM  NSP
0     120  0.000  0.000    2
1     132  0.006  0.000    1
2     133  0.003  0.000    1
3     134  0.003  0.000    1
4     132  0.007  0.000    1
...   ...    ...    ...  ...
2121  140  0.000  0.000    2
2122  140  0.001  0.000    2
2123  140  0.001  0.000    2
2124  140  0.001  0.000    2
2125  142  0.002  0.002    1

[2126 rows x 4 columns]

In [4]:
ctg=pd.read_csv(r"C:\Users\user\Desktop\MLA\CTG.csv")

In [5]:
ctg.isnull().sum()[ctg.isnull().sum()>0]

Series([], dtype: int64)

In [6]:
ctg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LB      2126 non-null   int64
 1   AC      2126 non-null   float64
 2   FM      2126 non-null   float64
 3   NSP     2126 non-null   int64
dtypes: float64(2), int64(2)
memory usage: 66.6 KB

In [7]:
from sklearn.model_selection import train_test_split
ctg_train,ctg_test=train_test_split(ctg,test_size=.2)

In [8]:
# over sampling
#df3=ctg_train[ctg_train.NSP==3]
#df2=ctg_train[ctg_train.NSP==2]

#ctg_train=pd.concat([ctg_train,df3,df3,df2,df2])
#ctg_train.shape

In [9]:
ctg.NSP.value_counts()

NSP
1    1655
2     295
3     176
Name: count, dtype: int64

In [10]:
ctg_train_x=ctg_train.iloc[:,0:-1]
ctg_train_y=ctg_train.iloc[:,-1]

ctg_test_x=ctg_test.iloc[:,0:-1]
ctg_test_y=ctg_test.iloc[:,-1]

In [11]:
from sklearn.tree import DecisionTreeClassifier
dt_ctg=DecisionTreeClassifier(class_weight='balanced')

In [12]:
dt_ctg.fit(ctg_train_x,ctg_train_y)

DecisionTreeClassifier(class_weight='balanced')

In [13]:
pred_test_ctg=dt_ctg.predict(ctg_test_x)
pred_test_ctg

array([2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 3, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 3,
       2, 1, 3, 1, 3, 2, 1, 1, 2, 1, 2, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 2,
       2, 1, 1, 3, 1, 1, 1, 3, 2, 1, 2, 3, 2, 2, 3, 2, 2, 1, 1, 1, 1, 1,
       1, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3,
       1, 1, 1, 1, 2, 2, 1, 2, 3, 1, 2, 1, 2, 1, 3, 1, 2, 1, 1, 1, 1, 3,
       1, 1, 1, 1, 2, 3, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 3, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 2, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 3, 3, 3, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 3, 1,
       3, 1, 1, 2, 2, 1, 1, 2, 3, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       3, 3, 1, 1, 1, 3, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1,
       1, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 3, 3, 1, 3, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1, 3, 2, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 2, 3, 1, 2, 1, 1, 1,
       2, 2, 3, 1, 1, 2, 1, 1, 3, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 3, 2, 2, 2, 1, 1, 3, 1, 3, 1, 1, 1,
       1, 2, 1, 1, 2, 1, 2, 1])

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [15]:
pred_tab_ctg= confusion_matrix(ctg_test_y,pred_test_ctg)

In [16]:
pred_tab_ctg

array([[286,  45,  27],
       [  4,  31,   4],
       [  1,   5,  23]])

In [17]:
accuracy_score(ctg_test_y,pred_test_ctg)

0.7981220657276995

In [18]:
precision_score(ctg_test_y,pred_test_ctg,average='macro')

0.5971532815748165

In [19]:
recall_score(ctg_test_y,pred_test_ctg,average='macro')

0.7956193082373009

In [20]:
f1_score(ctg_test_y,pred_test_ctg,average='macro')

0.6507464887799786

# Grid Search

In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
search_dict = {'criterion':['gini','entropy'],
              'max_depth':range(4,9),
              'min_samples_split':[50,75,100]}

In [23]:
dt_ctg=DecisionTreeClassifier()
grid=GridSearchCV(dt_ctg,param_grid=search_dict)

In [24]:
grid.fit(ctg_train_x,ctg_train_y)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(4, 9),
                         'min_samples_split': [50, 75, 100]})

In [25]:
grid.best_params_

{'criterion': 'entropy', 'max_depth': 7, 'min_samples_split': 100}

# Random Search

In [1]:
from sklearn.model_selection import RandomizedSearchCV

In [2]:
search_dict1 = {'criterion':['gini','entropy'],
              'max_depth':range(4,9),
              'min_samples_split':[50,75,100]}

In [3]:
dt_ctg=DecisionTreeClassifier()

NameError: name 'DecisionTreeClassifier' is not defined

In [ ]:
random_search=RandomizedSearchCV(
        estimator=dt_ctg,
        param_distributions=search_dict1,
        n_iter=10,
        random_state=42,
        cv=5
)

In [ ]:

random_search.fit(ctg_train_x,ctg_train_y)

In [ ]:
random_search.best_params_

In [46]:

tab_ctg_df=pd.DataFrame(pred_tab_ctg)
tab_ctg_df.columns=['Normal','suspect','pathalogical']
tab_ctg_df.index=['Normal','suspect','pathalogical']

In [47]:
tab_ctg_df

              Normal  suspect  pathalogical
Normal           286       45            27
suspect            4       31             4
pathalogical       1        5            23

In [48]:
#%pip install pydotplus

Requirement already satisfied: pydotplus in c:\users\user\anaconda3\lib\site-packages (2.0.2)
Requirement already satisfied: pyparsing>=2.0.1 in c:\users\user\anaconda3\lib\site-packages (from pydotplus) (3.2.5)
Note: you may need to restart the kernel to use updated packages.

In [49]:
#%pip install pydot

Requirement already satisfied: pydot in c:\users\user\anaconda3\lib\site-packages (4.0.1)
Requirement already satisfied: pyparsing>=3.1.0 in c:\users\user\anaconda3\lib\site-packages (from pydot) (3.2.5)
Note: you may need to restart the kernel to use updated packages.

In [50]:
#%pip install dot

Requirement already satisfied: dot in c:\users\user\anaconda3\lib\site-packages (0.3.0)
Note: you may need to restart the kernel to use updated packages.

In [51]:
conda install graphviz

Jupyter detected...
3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.7.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [52]:
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus




import pydot
from six import StringIO

In [53]:
dt_ctg.fit(dt_ctg_train_x,dt_ctg_train_y)

NameError: name 'dt_ctg_train_x' is not defined

In [ ]:
dot_data = StringIO()

import matplotlib.pyplot as plt
fig= plt.figure(figsize=(12,12))

export_graphviz(dt_ctg  , out_file=dot_data,
                filled=True, rounded=True,
                special_characters=True , feature_names=ctg_train_x.columns  )
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

(graph,) = pydot.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

# trainRF

In [ ]:
import pandas as pd

In [ ]:
pd.read_csv(r"C:\Users\user\Desktop\MLA\trainRF.csv")

In [ ]:
mp=pd.read_csv(r"C:\Users\user\Desktop\MLA\trainRF.csv")

In [ ]:
mp.isnull().sum()[mp.isnull().sum()>0]

In [ ]:
#mp.info()

In [ ]:
from sklearn.model_selection import train_test_split
mp_train,mp_test=train_test_split(mp,test_size=.2)

In [ ]:
mp_train_x=mp_train.iloc[:,0:-1]
mp_train_y=mp_train.iloc[:,-1]

mp_test_x=mp_test.iloc[:,0:-1]
mp_test_y=mp_test.iloc[:,-1]

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt_mp=DecisionTreeClassifier(criterion='entropy',min_samples_split=50)

In [ ]:
dt_mp.fit(mp_train_x,mp_train_y)

In [ ]:
pred_test_mp=dt_mp.predict(mp_test_x)
pred_test_mp

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [ ]:
tab_mp= confusion_matrix(mp_test_y,pred_test_mp)

In [ ]:
tab_mp

In [ ]:
accuracy_score(mp_test_y,pred_test_mp)

In [ ]:
recall_score(mp_test_y,pred_test_mp,average='macro')

In [ ]:
precision_score(mp_test_y,pred_test_mp,average='macro')

In [ ]:
f1_score(mp_test_y,pred_test_mp,average='macro')

# Grid Search

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
search_dict = {'criterion':['gini','entropy'],
              'max_depth':range(4,9),
              'min_samples_split':[50,75,100]}

In [ ]:
dt=DecisionTreeClassifier()
grid=GridSearchCV(dt,param_grid=search_dict)

In [ ]:
grid.fit(mp_train_x,mp_train_y)

In [ ]:
grid.best_params_

In [ ]:
#grid search best combination from gini,entropy,min_sampling_split,max_depth

In [ ]:
#%pip install pydotplus

In [ ]:
#%pip install pydot

In [ ]:
#%pip install dot

In [ ]:
#conda install graphviz

In [ ]:
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
import pydot
from six import StringIO

In [ ]:
dot_data = StringIO()

import matplotlib.pyplot as plt
fig= plt.figure(figsize=(12,12))

export_graphviz(dt_mp  , out_file=dot_data,
                filled=True, rounded=True,
                special_characters=True , feature_names=mp_train_x.columns  )
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

(graph,) = pydot.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())